artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: paddy-disease-classification
  local_data_file: artifacts/data_ingestion
  class_weight: artifacts/class_weight.json