artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: paddy-disease-classification
  local_data_file: artifacts/data_ingestion
  class_weight: artifacts/class_weight.json

prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.pth
    updated_base_model_path: artifacts/prepare_base_model/updated_base_model.pth
